# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: budget.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'budget.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62udget.proto\x12\x06\x62udget\"\x1b\n\rBudgetRequest\x12\n\n\x02id\x18\x01 \x01(\x05\",\n\x0e\x42udgetResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\x32K\n\rBudgetService\x12:\n\tGetBudget\x12\x15.budget.BudgetRequest\x1a\x16.budget.BudgetResponseBB\n\x1amadro.finances.budget.grpcB\x0b\x42udgetProtoP\x01Z\x15\x66inances/proto/budgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'budget_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032madro.finances.budget.grpcB\013BudgetProtoP\001Z\025finances/proto/budget'
  _globals['_BUDGETREQUEST']._serialized_start=24
  _globals['_BUDGETREQUEST']._serialized_end=51
  _globals['_BUDGETRESPONSE']._serialized_start=53
  _globals['_BUDGETRESPONSE']._serialized_end=97
  _globals['_BUDGETSERVICE']._serialized_start=99
  _globals['_BUDGETSERVICE']._serialized_end=174
# @@protoc_insertion_point(module_scope)
