/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package madro.finances.budget;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

@SpringBootApplication(exclude = {
    net.devh.boot.grpc.server.autoconfigure.GrpcServerSecurityAutoConfiguration.class
})
@ComponentScan(basePackages = {"madro.finances.budget"})
public class App {
    
	public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
