spring:
 config:
   import: optional:file:.env[.properties]
 datasource:
   url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
   username: ${database.credentials.username}
   password: ${database.credentials.password}
   driver-class-name: com.mysql.cj.jdbc.Driver

 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
   properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
